services:
  - type: web
    name: bolt-backend
    runtime: node
    region: singapore
    buildCommand: npm install
    startCommand: npm run prod
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: YOUR_SUPABASE_URL
      - key: SUPABASE_KEY
        value: YOUR_SUPABASE_KEY
    autoDeploy: true
    plan: starter